import type { WordCreateInput } from '@i-speak-hello/shared';

export const SEED_WORDS: WordCreateInput[] = [
  // ── Mandarin (25 words) ──────────────────────────
  { targetLanguage: 'zh', original: '你好', translation: 'halo', pinyin: 'nǐ hǎo', source: 'seed' },
  { targetLanguage: 'zh', original: '谢谢', translation: 'terima kasih', pinyin: 'xiè xie', source: 'seed' },
  { targetLanguage: 'zh', original: '对不起', translation: 'maaf', pinyin: 'duì bu qǐ', source: 'seed' },
  { targetLanguage: 'zh', original: '再见', translation: 'sampai jumpa', pinyin: 'zài jiàn', source: 'seed' },
  { targetLanguage: 'zh', original: '是', translation: 'ya / benar', pinyin: 'shì', source: 'seed' },
  { targetLanguage: 'zh', original: '不', translation: 'tidak', pinyin: 'bù', source: 'seed' },
  { targetLanguage: 'zh', original: '我', translation: 'saya', pinyin: 'wǒ', source: 'seed' },
  { targetLanguage: 'zh', original: '你', translation: 'kamu', pinyin: 'nǐ', source: 'seed' },
  { targetLanguage: 'zh', original: '他', translation: 'dia (laki-laki)', pinyin: 'tā', source: 'seed' },
  { targetLanguage: 'zh', original: '她', translation: 'dia (perempuan)', pinyin: 'tā', source: 'seed' },
  { targetLanguage: 'zh', original: '吃', translation: 'makan', pinyin: 'chī', source: 'seed' },
  { targetLanguage: 'zh', original: '喝', translation: 'minum', pinyin: 'hē', source: 'seed' },
  { targetLanguage: 'zh', original: '水', translation: 'air', pinyin: 'shuǐ', source: 'seed' },
  { targetLanguage: 'zh', original: '大', translation: 'besar', pinyin: 'dà', source: 'seed' },
  { targetLanguage: 'zh', original: '小', translation: 'kecil', pinyin: 'xiǎo', source: 'seed' },
  { targetLanguage: 'zh', original: '好', translation: 'baik / bagus', pinyin: 'hǎo', source: 'seed' },
  { targetLanguage: 'zh', original: '朋友', translation: 'teman', pinyin: 'péng yǒu', source: 'seed' },
  { targetLanguage: 'zh', original: '学习', translation: 'belajar', pinyin: 'xué xí', source: 'seed' },
  { targetLanguage: 'zh', original: '工作', translation: 'bekerja', pinyin: 'gōng zuò', source: 'seed' },
  { targetLanguage: 'zh', original: '喜欢', translation: 'suka', pinyin: 'xǐ huān', source: 'seed' },
  { targetLanguage: 'zh', original: '今天', translation: 'hari ini', pinyin: 'jīn tiān', source: 'seed' },
  { targetLanguage: 'zh', original: '明天', translation: 'besok', pinyin: 'míng tiān', source: 'seed' },
  { targetLanguage: 'zh', original: '昨天', translation: 'kemarin', pinyin: 'zuó tiān', source: 'seed' },
  { targetLanguage: 'zh', original: '钱', translation: 'uang', pinyin: 'qián', source: 'seed' },
  { targetLanguage: 'zh', original: '很', translation: 'sangat', pinyin: 'hěn', source: 'seed' },

  // ── English (25 words) ───────────────────────────
  { targetLanguage: 'en', original: 'however', translation: 'namun / akan tetapi', source: 'seed' },
  { targetLanguage: 'en', original: 'therefore', translation: 'oleh karena itu', source: 'seed' },
  { targetLanguage: 'en', original: 'although', translation: 'meskipun', source: 'seed' },
  { targetLanguage: 'en', original: 'meanwhile', translation: 'sementara itu', source: 'seed' },
  { targetLanguage: 'en', original: 'nevertheless', translation: 'meskipun demikian', source: 'seed' },
  { targetLanguage: 'en', original: 'accomplish', translation: 'mencapai / menyelesaikan', source: 'seed' },
  { targetLanguage: 'en', original: 'determine', translation: 'menentukan', source: 'seed' },
  { targetLanguage: 'en', original: 'significant', translation: 'penting / berarti', source: 'seed' },
  { targetLanguage: 'en', original: 'acknowledge', translation: 'mengakui', source: 'seed' },
  { targetLanguage: 'en', original: 'consequence', translation: 'akibat / konsekuensi', source: 'seed' },
  { targetLanguage: 'en', original: 'gradually', translation: 'secara bertahap', source: 'seed' },
  { targetLanguage: 'en', original: 'inevitable', translation: 'tidak terhindarkan', source: 'seed' },
  { targetLanguage: 'en', original: 'persuade', translation: 'membujuk', source: 'seed' },
  { targetLanguage: 'en', original: 'reluctant', translation: 'enggan', source: 'seed' },
  { targetLanguage: 'en', original: 'thoroughly', translation: 'secara menyeluruh', source: 'seed' },
  { targetLanguage: 'en', original: 'ambitious', translation: 'ambisius', source: 'seed' },
  { targetLanguage: 'en', original: 'peculiar', translation: 'aneh / ganjil', source: 'seed' },
  { targetLanguage: 'en', original: 'compromise', translation: 'kompromi', source: 'seed' },
  { targetLanguage: 'en', original: 'emphasize', translation: 'menekankan', source: 'seed' },
  { targetLanguage: 'en', original: 'fundamental', translation: 'mendasar / fundamental', source: 'seed' },
  { targetLanguage: 'en', original: 'genuine', translation: 'asli / tulus', source: 'seed' },
  { targetLanguage: 'en', original: 'hesitate', translation: 'ragu-ragu', source: 'seed' },
  { targetLanguage: 'en', original: 'influence', translation: 'pengaruh / mempengaruhi', source: 'seed' },
  { targetLanguage: 'en', original: 'obstacle', translation: 'hambatan / rintangan', source: 'seed' },
  { targetLanguage: 'en', original: 'remarkable', translation: 'luar biasa', source: 'seed' },
];
